// Code generated by scripts/gen-players.py from shared/players.json; DO NOT EDIT.
//
// 接一个新播放器:改那份 JSON → 跑 `python3 scripts/gen-players.py`。
// CI 跑 `--check` 对账,手改这里会红。

package main

// 播放器标识 —— 跟 Swift 侧 PlaybackPlayer 的 rawValue 逐字对应,
// 共享文件 lyrimuse-features.json 里 "players" 字段的取值。
const (
	playerAppleMusic = "apple_music"
	playerQQMusic    = "qq_music"
	playerNetease    = "netease_music"
	playerKugou      = "kugou_music"
	playerSoda       = "soda_music"
	playerSpotify    = "spotify"
	playerAuto       = "auto"
)

// 各播放器的 App bundle id。
const (
	appleMusicBundleID   = "com.apple.Music"
	qqMusicBundleID      = "com.tencent.QQMusicMac"
	neteaseMusicBundleID = "com.netease.163music"
	kugouMusicBundleID   = "com.kugou.mac.Music"
	sodaMusicBundleID    = "com.soda.music"
	spotifyBundleID      = "com.spotify.client"
)

// allPlayerIDs 是 "players" 字段的全部合法取值(含 auto),isValidPlayerValue 用。
var allPlayerIDs = []string{
	playerAppleMusic,
	playerQQMusic,
	playerNetease,
	playerKugou,
	playerSoda,
	playerSpotify,
	playerAuto,
}

// playerBundleIDs 是「播放器标识 → bundle id」。auto 不在表里 —— 它没有固定目标,
// 调用方(playerBundleID)自己决定查不到时退回哪个。
var playerBundleIDs = map[string]string{
	playerAppleMusic: appleMusicBundleID,
	playerQQMusic:    qqMusicBundleID,
	playerNetease:    neteaseMusicBundleID,
	playerKugou:      kugouMusicBundleID,
	playerSoda:       sodaMusicBundleID,
	playerSpotify:    spotifyBundleID,
}

// builtinPlayerBundleIDs 是内置播放器的 bundle id 集合 —— isKnownPlayerBundleID
// (自动识别的准入名单)和 resolveTrustedPlayers(把内置的从信任列表里剔掉)共用。
var builtinPlayerBundleIDs = map[string]bool{
	appleMusicBundleID:   true,
	qqMusicBundleID:      true,
	neteaseMusicBundleID: true,
	kugouMusicBundleID:   true,
	sodaMusicBundleID:    true,
	spotifyBundleID:      true,
}

// playerProcessNames 是「播放器标识 → 可执行文件名」,companion-launch 的 pgrep -x 用。
// pgrep 比的是内核 p_comm(16 字节上限,UTF-8 下中文名要数字节),加新播放器时要核。
var playerProcessNames = map[string]string{
	playerAppleMusic: "Music",
	playerQQMusic:    "QQMusic",
	playerNetease:    "NeteaseMusic",
	playerKugou:      "酷狗音乐",
	playerSoda:       "汽水音乐",
	playerSpotify:    "Spotify",
}

// knownPlayerProcessNames 是上表的全部取值 —— 选了「自动识别」时盯全部。
var knownPlayerProcessNames = []string{"Music", "QQMusic", "NeteaseMusic", "酷狗音乐", "汽水音乐", "Spotify"}

// playerScrobbleLabels 是「bundle id → ListenBrainz 的 media_player 标签」。
var playerScrobbleLabels = map[string]string{
	appleMusicBundleID:   "Apple Music (macOS)",
	qqMusicBundleID:      "QQ Music (macOS)",
	neteaseMusicBundleID: "NetEase Cloud Music (macOS)",
	kugouMusicBundleID:   "Kugou Music (macOS)",
	sodaMusicBundleID:    "Soda Music (macOS)",
	spotifyBundleID:      "Spotify (macOS)",
}

// defaultScrobbleLabel:既不是内置播放器、也不在信任列表里时的兜底标签。
const defaultScrobbleLabel = "Apple Music (macOS)"

// playerNativeLyricSources 是「播放器标识 → 它自家的歌词源」——用它听歌时
// 优先选它自己的歌词(时间轴跟它的音频母版对得上)。没有自家源的播放器不在表里。
var playerNativeLyricSources = map[string]string{
	playerAppleMusic: "applemusic",
	playerQQMusic:    "qq",
	playerNetease:    "netease",
	playerKugou:      "kugou",
	playerSoda:       "soda",
}

// playerRepublishesZeroAnchor 是「bundle id → 开播那个 elapsed=0 锚点会不会被原样
// 重发一次」。只列**实测见过**的播放器:真起播点是连发里的哪一个,各家相反
// (汽水音乐/网易云是第一个,Apple Music 是最后一个),判反 = 整首歌恒定偏移。
// 判定本身在 isStaleAnchorRepublish,Swift 侧 republishesZeroAnchor 同源。
var playerRepublishesZeroAnchor = map[string]bool{
	neteaseMusicBundleID: true,
	sodaMusicBundleID:    true,
	spotifyBundleID:      true,
}
