#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""从 shared/lyric-notices.json 生成 Swift / Go 两侧的歌词声明行规则。

# 为什么需要它

歌词源塞进歌词里的声明行(「TME享有本翻译作品的著作权」「未经著作权人许可不得翻录翻唱或使用」
「本字幕由AI语音对齐技术生成」…)两边都要认:引擎清洗译文轨,App 过滤正文显示。两边各写
一份,同一句声明就会只有一边认得。规则本体放在那份 JSON 里,这里生成四个文件:

- lyrimuse/Sources/LyrimuseCore/Lyrics/LyricNotices+Generated.swift   规则表(App)
- lyrimuse/Sources/lyrimuse-selftest/LyricNoticeExamples+Generated.swift  例句(selftest)
- lyrimuse-engine/lyricnotices_generated.go        规则表(引擎)
- lyrimuse-engine/lyricnotices_generated_test.go   例句(go test)

两侧的匹配逻辑手写在 LyricNotices.swift / lyricnotices.go 里,这里只生成数据。

# 正则写法

Go 用 RE2,App 用 NSRegularExpression(ICU),两者只在一个公共子集上语义一致。下面这些写法
要么一边不支持,要么两边结果不同,一律拒收:\\b \\B(RE2 只按 ASCII 判单词边界)、前后查看、
反向引用、原子组、占有量词、命名组、内联标志(大小写走 ignoreCase 字段)、\\Q…\\E、\\X、\\R、\\h。
两侧测试再各跑一遍全部例句,把剩下的差别兜住。

# 字段

- id          规则名,两侧测试按它报错
- note        一句话说明这条认的是什么
- pattern     正则
- ignoreCase  拉丁字母忽略大小写
- scopes      translation(引擎清洗译文轨)/ body(App 正文署名过滤),至少一个
- drop        本条必须命中的例句,至少一句
- keep        任何一条规则都不许命中的例句
"""
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "shared" / "lyric-notices.json"

CORE_SWIFT = "lyrimuse/Sources/LyrimuseCore/Lyrics/LyricNotices+Generated.swift"
TEST_SWIFT = "lyrimuse/Sources/lyrimuse-selftest/LyricNoticeExamples+Generated.swift"
GO_FILE = "lyrimuse-engine/lyricnotices_generated.go"
GO_TEST = "lyrimuse-engine/lyricnotices_generated_test.go"

BANNER_SWIFT = (
    "// 由 scripts/gen-lyric-notices.py 从 shared/lyric-notices.json 生成,请勿手改。\n"
    "// 改规则:改那份 JSON → 跑 `python3 scripts/gen-lyric-notices.py`。CI 跑 `--check` 对账,手改这里会红。\n"
)
BANNER_GO = (
    "// Code generated by scripts/gen-lyric-notices.py from shared/lyric-notices.json; DO NOT EDIT.\n"
    "//\n"
    "// 改规则:改那份 JSON → 跑 `python3 scripts/gen-lyric-notices.py`。CI 跑 `--check` 对账,手改这里会红。\n"
)

SCOPES = ("translation", "body")

# 两个引擎语义不一致或一边不支持的写法。
FORBIDDEN = [
    (r"\\[bB]", "\\b / \\B"),
    (r"\(\?[=!]", "前向查看"),
    (r"\(\?<[=!]", "后向查看"),
    (r"\\[1-9]", "反向引用"),
    (r"\(\?>", "原子组"),
    (r"[*+?}]\+", "占有量词"),
    (r"\(\?P?<", "命名组"),
    (r"\(\?[a-zA-Z-]+[:)]", "内联标志"),
    (r"\\[QEXRhk]", "\\Q \\E \\X \\R \\h \\k"),
]


def fail(msg):
    sys.exit("shared/lyric-notices.json: " + msg)


def load():
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    rules = spec["rules"]
    seen = set()
    for r in rules:
        rid = r.get("id") or fail("有一条规则没有 id")
        if rid in seen:
            fail(f"id 重复: {rid}")
        seen.add(rid)
        for key in ("pattern", "note"):
            if not isinstance(r.get(key), str) or not r[key]:
                fail(f"{rid}: 缺 {key}")
        if not isinstance(r.get("ignoreCase"), bool):
            fail(f"{rid}: ignoreCase 必须是 true / false")
        scopes = r.get("scopes") or []
        if not scopes or any(s not in SCOPES for s in scopes):
            fail(f"{rid}: scopes 只能取 {SCOPES},至少一个")
        if not r.get("drop"):
            fail(f"{rid}: drop 至少要有一句")
        for pat, what in FORBIDDEN:
            if re.search(pat, r["pattern"]):
                fail(f"{rid}: 正则用了两边语义不一致的写法({what}): {r['pattern']}")
    return rules


def gofmt(text):
    """过一遍 gofmt:CI 第一步就是 gofmt -l。--check 与写盘走同一条路径。"""
    exe = shutil.which("gofmt")
    if not exe:
        print("  ! 没找到 gofmt,Go 生成物未格式化(CI 的 gofmt 检查会红)")
        return text
    done = subprocess.run([exe], input=text, capture_output=True, text=True)
    if done.returncode != 0:
        sys.exit("gofmt 失败:\n" + done.stderr)
    return done.stdout


def quote(s):
    """Go 与 Swift 的普通字符串字面量在这几个转义上写法相同。"""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def examples(rules):
    out = []
    for r in rules:
        out += [(r["id"], t, True) for t in r["drop"]]
        out += [(r["id"], t, False) for t in r.get("keep", [])]
    return out


def render_go(rules):
    lines = [BANNER_GO, "\npackage main\n\n", "var lyricNoticeRules = []lyricNoticeRule{\n"]
    for r in rules:
        lines.append(
            "\t{id: %s, pattern: %s, ignoreCase: %s, translation: %s, body: %s},\n"
            % (quote(r["id"]), quote(r["pattern"]), str(r["ignoreCase"]).lower(),
               str("translation" in r["scopes"]).lower(), str("body" in r["scopes"]).lower()))
    lines.append("}\n")
    return "".join(lines)


def render_go_test(rules):
    lines = [BANNER_GO, "\npackage main\n\n",
             "// drop = true:rule 这一条必须命中;false:任何一条规则都不许命中。\n",
             "var lyricNoticeExamples = []struct {\n\trule string\n\ttext string\n\tdrop bool\n}{\n"]
    for rid, text, drop in examples(rules):
        lines.append("\t{%s, %s, %s},\n" % (quote(rid), quote(text), str(drop).lower()))
    lines.append("}\n")
    return "".join(lines)


def render_core_swift(rules):
    lines = [BANNER_SWIFT, "\nextension LyricNotices {\n", "    static let rules: [Rule] = [\n"]
    for r in rules:
        lines.append(
            "        Rule(id: %s, pattern: %s, ignoreCase: %s, translation: %s, body: %s),\n"
            % (quote(r["id"]), quote(r["pattern"]), str(r["ignoreCase"]).lower(),
               str("translation" in r["scopes"]).lower(), str("body" in r["scopes"]).lower()))
    lines.append("    ]\n}\n")
    return "".join(lines)


def render_test_swift(rules):
    lines = [BANNER_SWIFT, "\n", "// drop = true:rule 这一条必须命中;false:任何一条规则都不许命中。\n",
             "let lyricNoticeExamples: [(rule: String, text: String, drop: Bool)] = [\n"]
    for rid, text, drop in examples(rules):
        lines.append("    (%s, %s, %s),\n" % (quote(rid), quote(text), str(drop).lower()))
    lines.append("]\n")
    return "".join(lines)


def main():
    check = "--check" in sys.argv[1:]
    rules = load()
    rendered = {
        GO_FILE: gofmt(render_go(rules)),
        GO_TEST: gofmt(render_go_test(rules)),
        CORE_SWIFT: render_core_swift(rules),
        TEST_SWIFT: render_test_swift(rules),
    }
    stale = []
    for rel, text in rendered.items():
        path = ROOT / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            print("  = %s" % rel)
            continue
        if check:
            stale.append(rel)
            print("  ✗ %s 与 shared/lyric-notices.json 对不上" % rel)
            continue
        path.write_text(text, encoding="utf-8")
        print("  → %s %s" % (rel, "(新建)" if current is None else "(更新)"))
    if check and stale:
        print("\n✗ 生成物过期或被手改。跑 `python3 scripts/gen-lyric-notices.py` 重新生成后再提交。")
        return 1
    print("\n✓ %d 条声明行规则,两侧生成物与 shared/lyric-notices.json 一致" % len(rules))
    return 0


if __name__ == "__main__":
    sys.exit(main())
