#!/usr/bin/env python3
"""从 shared/players.json 生成 Swift / Go 两侧的内置播放器表。

# 为什么需要它

接一个内置播放器之前要改 15 处左右:Swift 侧的 enum case、bundleIdentifier、displayName、
tintColor、fallbackSymbolName、bundledIconResourceName、displayOrder、位置档位登记;Go 侧的
playerXxx 常量、xxxBundleID 常量、isValidPlayerValue、isKnownPlayerBundleID、
resolveTrustedPlayers 的内置表、playerBundleID、mediaPlayerLabel、knownPlayerProcessNames、
playerProcessNameFor、playerNativeLyricSource。每一处都写着「两侧必须同步维护」——
而注释拦不住漏改(ytmusicad.go 那条逐字比对守卫就是被同一类漏改逼出来的)。

现在这些表全部从 shared/players.json 生成,接一个播放器 = 加一条 JSON + 一张品牌图标。
CI 跑 `--check` 保证生成物没被手改、也没忘记重新生成。

# 刻意不生成的东西

只生成「每个播放器一行数据」的机械映射。真正有判断的地方(auto 的三级解析树、Apple Music
那条 AppleScript 路径、广告探针、伺服参数)全部留在手写文件里——把逻辑塞进生成器只会让
它变成第二个需要读懂的地方。

# 字段

- id            播放器标识,Swift rawValue 与 Go 常量的值,共享 features.json 里 players 的取值
- swiftCase     Swift enum 的 case 名
- goConst       Go 常量名(命名不机械:netease_music → playerNetease,所以显式给)
- bundleID      App bundle id;auto 是空字符串(没有固定目标,调用方据此 no-op)
- goBundleConst Go 侧 bundle id 常量名;auto 为 null
- processName   可执行文件名,companion-launch 的 pgrep -x 用;auto 为 null
                内核 p_comm 上限 16 字节,UTF-8 中文名要数字节
- displayName   {"literal": …} 直接用 / {"l10n": …} 走 L10n.t(词条要在 .strings 里登记)
- scrobbleLabel ListenBrainz 的 media_player 标签;auto 为 null
                apple_music 那条同时是「认不出来源」时的兜底值
- nativeLyricSource  它自家的歌词源(同源加权 +250);没有就 null
- positionTier  precise / cleanExtrapolated / noisyFloored;auto 为 null
- republishesZeroAnchor  开播那个 elapsed=0 锚点会不会被这个播放器原样重发一次;auto 为 null
                只给**实测见过**的播放器置 true:判反的代价是整首歌恒定偏移
- playingFromRate  这个播放器报的 `playing:false` 不可信、要按 `playbackRate > 0` 判在不在播;auto 为 null
                只给**实测见过**的播放器置 true(酷狗单曲循环回到开头时报 playing:false、rate 仍是 1,
                真暂停时 rate 归 0)。判定本身在 MediaControlClient.effectivePlaying / effectivePlaying(Go)
- needsAutomationPermission  这个播放器要不要 macOS 的「自动化」权限(我们向它发 Apple Event);auto 为 null
                = 它有 AppleScript 字典、且本仓真的在用。只生成 Swift 侧:collector 是独立
                签名身份、TCC 里是另一条记录,那边没有 API 能查或触发它
- needsFullDiskAccess  collector 读它的客户端文件要不要「完全磁盘访问」;auto 为 null
                = 那些文件在 `~/Library/Containers/` 下(App 带沙盒)。collector 侧
                TestPlayersNeedFullDiskAccessMatchesClientPaths 按真实路径对账,填错会红
- tint          {"rgb": [r,g,b]} / {"source": "…"}(复用歌词来源配色) / {"secondary": true}
- fallbackSymbol      没装这个 App、也没有随包图标时的 SF Symbol
- bundledIcon   随包打包的品牌图资源名;没有就 null
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "shared" / "players.json"

CORE_SWIFT = "lyrimuse/Sources/LyrimuseCore/Local/PlaybackPlayer+Generated.swift"
APP_SWIFT = "lyrimuse/Sources/lyrimuse/Settings/PlaybackPlayerMeta+Generated.swift"
GO_FILE = "lyrimuse-collector/players_generated.go"

BANNER_SWIFT = (
    "// 由 scripts/gen-players.py 从 shared/players.json 生成,请勿手改。\n"
    "// 接一个新播放器:改那份 JSON → 跑 `python3 scripts/gen-players.py` → 补一张品牌图标。\n"
    "// CI 跑 `--check` 对账,手改这里会红。\n"
)
BANNER_GO = (
    "// Code generated by scripts/gen-players.py from shared/players.json; DO NOT EDIT.\n"
    "//\n"
    "// 接一个新播放器:改那份 JSON → 跑 `python3 scripts/gen-players.py`。\n"
    "// CI 跑 `--check` 对账,手改这里会红。\n"
)


def load():
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    players = spec["players"]
    by_id = {p["id"]: p for p in players}
    for group, order in spec["displayOrder"].items():
        if group.startswith("$"):
            continue
        missing = [i for i in order if i not in by_id]
        extra = [p["id"] for p in players if p["id"] not in order]
        if missing or extra:
            sys.exit(f"displayOrder.{group} 与 players 对不上: 多出 {missing} / 漏了 {extra}")
    return spec, players, by_id


def gofmt(text):
    """把渲染结果过一遍 gofmt —— CI 第一步就是 gofmt -l,生成物当然也得是格式化过的。

    找不到 gofmt 时原样返回并提示:本地没装 Go 也该能改 JSON 重新生成,CI 那边照样会红。
    --check 与写盘走同一条路径,否则两边会因为格式化与否得出不同结论。
    """
    exe = shutil.which("gofmt")
    if not exe:
        print("  ! 没找到 gofmt,Go 生成物未格式化(CI 的 gofmt 检查会红)")
        return text
    done = subprocess.run([exe], input=text, capture_output=True, text=True)
    if done.returncode != 0:
        sys.exit("gofmt 失败:\n" + done.stderr)
    return done.stdout


def go_quote(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


# ---------------------------------------------------------------- Go

def render_go(spec, players):
    concrete = [p for p in players if p["id"] != "auto"]
    out = [BANNER_GO, "\npackage main\n"]

    out.append("\n// 播放器标识 —— 跟 Swift 侧 PlaybackPlayer 的 rawValue 逐字对应,\n"
               "// 共享文件 lyrimuse-features.json 里 \"players\" 字段的取值。\nconst (\n")
    width = max(len(p["goConst"]) for p in players)
    for p in players:
        out.append("\t%s = %s\n" % (p["goConst"].ljust(width), go_quote(p["id"])))
    out.append(")\n")

    out.append("\n// 各播放器的 App bundle id。\nconst (\n")
    consts = [p for p in concrete if p.get("goBundleConst")]
    width = max(len(p["goBundleConst"]) for p in consts)
    for p in consts:
        out.append("\t%s = %s\n" % (p["goBundleConst"].ljust(width), go_quote(p["bundleID"])))
    out.append(")\n")

    out.append("\n// allPlayerIDs 是 \"players\" 字段的全部合法取值(含 auto),isValidPlayerValue 用。\n"
               "var allPlayerIDs = []string{\n")
    for p in players:
        out.append("\t%s,\n" % p["goConst"])
    out.append("}\n")

    out.append("\n// playerBundleIDs 是「播放器标识 → bundle id」。auto 不在表里 —— 它没有固定目标,\n"
               "// 调用方(playerBundleID)自己决定查不到时退回哪个。\n"
               "var playerBundleIDs = map[string]string{\n")
    for p in concrete:
        out.append("\t%s: %s,\n" % (p["goConst"], p["goBundleConst"]))
    out.append("}\n")

    out.append("\n// builtinPlayerBundleIDs 是内置播放器的 bundle id 集合 —— isKnownPlayerBundleID\n"
               "// (自动识别的准入名单)和 resolveTrustedPlayers(把内置的从信任列表里剔掉)共用。\n"
               "var builtinPlayerBundleIDs = map[string]bool{\n")
    for p in concrete:
        out.append("\t%s: true,\n" % p["goBundleConst"])
    out.append("}\n")

    out.append("\n// playerProcessNames 是「播放器标识 → 可执行文件名」,companion-launch 的 pgrep -x 用。\n"
               "// pgrep 比的是内核 p_comm(16 字节上限,UTF-8 下中文名要数字节),加新播放器时要核。\n"
               "var playerProcessNames = map[string]string{\n")
    for p in concrete:
        out.append("\t%s: %s,\n" % (p["goConst"], go_quote(p["processName"])))
    out.append("}\n")

    out.append("\n// knownPlayerProcessNames 是上表的全部取值 —— 选了「自动识别」时盯全部。\n"
               "var knownPlayerProcessNames = []string{")
    out.append(", ".join(go_quote(p["processName"]) for p in concrete))
    out.append("}\n")

    out.append("\n// playerScrobbleLabels 是「bundle id → ListenBrainz 的 media_player 标签」。\n"
               "var playerScrobbleLabels = map[string]string{\n")
    for p in concrete:
        if p.get("scrobbleLabel"):
            out.append("\t%s: %s,\n" % (p["goBundleConst"], go_quote(p["scrobbleLabel"])))
    out.append("}\n")

    apple = next(p for p in players if p["id"] == "apple_music")
    out.append("\n// defaultScrobbleLabel:既不是内置播放器、也不在信任列表里时的兜底标签。\n"
               "const defaultScrobbleLabel = %s\n" % go_quote(apple["scrobbleLabel"]))

    out.append("\n// playerNativeLyricSources 是「播放器标识 → 它自家的歌词源」——用它听歌时\n"
               "// 优先选它自己的歌词(时间轴跟它的音频母版对得上)。没有自家源的播放器不在表里。\n"
               "var playerNativeLyricSources = map[string]string{\n")
    for p in concrete:
        if p.get("nativeLyricSource"):
            out.append("\t%s: %s,\n" % (p["goConst"], go_quote(p["nativeLyricSource"])))
    out.append("}\n")

    out.append("\n// playerNeedsFullDiskAccess 是「播放器标识 → collector 读它的客户端文件要不要\n"
               "// 「完全磁盘访问」」。只供 TestPlayersNeedFullDiskAccessMatchesClientPaths 对账:\n"
               "// 运行期判据是路径本身(localcacheprobe.go),不查这张表。\n"
               "var playerNeedsFullDiskAccess = map[string]bool{\n")
    for p in concrete:
        if p.get("needsFullDiskAccess"):
            out.append("\t%s: true,\n" % p["goConst"])
    out.append("}\n")

    out.append("\n// playerRepublishesZeroAnchor 是「bundle id → 开播那个 elapsed=0 锚点会不会被原样\n"
               "// 重发一次」。只列**实测见过**的播放器:真起播点是连发里的哪一个,各家相反\n"
               "// (汽水音乐/网易云是第一个,Apple Music 是最后一个),判反 = 整首歌恒定偏移。\n"
               "// 判定本身在 isStaleAnchorRepublish,Swift 侧 republishesZeroAnchor 同源。\n"
               "var playerRepublishesZeroAnchor = map[string]bool{\n")
    for p in concrete:
        if p.get("republishesZeroAnchor") and p.get("goBundleConst"):
            out.append("\t%s: true,\n" % p["goBundleConst"])
    out.append("}\n")

    out.append("\n// playerPlayingFromRate 是「bundle id → 这个播放器报的 playing:false 不可信、要按\n"
               "// playbackRate > 0 判在不在播」。只列**实测见过**的播放器。\n"
               "// 判定本身在 effectivePlaying,Swift 侧 playingFromRate 同源。\n"
               "var playerPlayingFromRate = map[string]bool{\n")
    for p in concrete:
        if p.get("playingFromRate") and p.get("goBundleConst"):
            out.append("\t%s: true,\n" % p["goBundleConst"])
    out.append("}\n")
    return "".join(out)


# ---------------------------------------------------------------- Swift (LyrimuseCore)

def render_core_swift(spec, players):
    concrete = [p for p in players if p["id"] != "auto"]
    out = [BANNER_SWIFT,
           "//\n// 这个类型为什么是「用户显式选择」而不是运行时自动判定、.auto 为什么是那条原则的\n"
           "// 例外、bundleIdentifier 为什么对 .auto 返回空字符串 —— 完整背景在 PlaybackPlayer.swift。\n\n"
           "import Foundation\n\n"
           "public enum PlaybackPlayer: String, CaseIterable, Identifiable, Codable, Hashable {\n"]
    for p in players:
        note = p.get("note")
        if note:
            out.append("    /// %s\n" % note)
        out.append('    case %s = "%s"\n' % (p["swiftCase"], p["id"]))
    out.append("\n    public var id: Self { self }\n")

    out.append("\n    /// 对应的 App bundle id。`.auto` 是空字符串 —— 它没有唯一目标,调用方据此\n"
               "    /// 自然地 no-op 掉「打开 Lyrimuse 时唤起播放器」这类需要具体 App 才成立的联动。\n"
               "    public var bundleIdentifier: String {\n        switch self {\n")
    for p in players:
        out.append('        case .%s: return "%s"\n' % (p["swiftCase"], p["bundleID"]))
    out.append("        }\n    }\n")

    out.append("\n    /// 这个播放器自家的歌词源(同源加权)。Go 侧 playerNativeLyricSources 同源。\n"
               "    public var nativeLyricSource: String? {\n        switch self {\n")
    for p in concrete:
        if p.get("nativeLyricSource"):
            out.append('        case .%s: return "%s"\n' % (p["swiftCase"], p["nativeLyricSource"]))
    out.append("        default: return nil\n        }\n    }\n")

    out.append("\n    /// 位置读数画像的标识(precise / cleanExtrapolated / noisyFloored)。\n"
               "    /// 映射成 `LocalPlaybackSource.PositionSourceTier` 在那边做 —— 那个枚举连同\n"
               "    /// 每一档的实测依据都属于伺服逻辑,不该跟着这张表走。\n"
               "    public var positionTierID: String? {\n        switch self {\n")
    for p in concrete:
        if p.get("positionTier"):
            out.append('        case .%s: return "%s"\n' % (p["swiftCase"], p["positionTier"]))
    out.append("        default: return nil\n        }\n    }\n")

    out.append("\n    /// 向这个播放器发 Apple Event 要不要 macOS 的「自动化」权限。\n"
               "    /// = 它有 AppleScript 字典、且本仓真的在用(读播放头 / 播放控制 / 取图床地址)。\n"
               "    /// 只覆盖 Lyrimuse 自己这一份身份:collector 是独立签名身份,TCC 里是另一条记录。\n"
               "    /// 消费点见 `Set<PlaybackPlayer>.playersNeedingAutomation`。\n"
               "    public var needsAutomationPermission: Bool {\n        switch self {\n")
    for p in concrete:
        if p.get("needsAutomationPermission"):
            out.append("        case .%s: return true\n" % p["swiftCase"])
    out.append("        default: return false\n        }\n    }\n")

    out.append("\n    /// collector 读这个播放器的客户端文件(歌词缓存 / 播放队列)要不要「完全磁盘访问」。\n"
               "    /// = 那些文件在 `~/Library/Containers/` 下;collector 侧有测试按真实路径对账。\n"
               "    /// 消费点见 `Set<PlaybackPlayer>.playersNeedingFullDiskAccess`。\n"
               "    public var needsFullDiskAccess: Bool {\n        switch self {\n")
    for p in concrete:
        if p.get("needsFullDiskAccess"):
            out.append("        case .%s: return true\n" % p["swiftCase"])
    out.append("        default: return false\n        }\n    }\n")

    out.append("\n    /// 开播那个 `elapsed == 0` 的锚点会不会被这个播放器原样重发一次。\n"
               "    /// 只有**实测见过**的播放器为 true:真起播点是连发里的哪一个,各家相反\n"
               "    /// (汽水音乐/网易云是第一个,Apple Music 是最后一个),判反 = 整首歌恒定偏移。\n"
               "    /// 判定本身在 `MediaControlClient.isStaleAnchorRepublish`,Go 侧同源。\n"
               "    public var republishesZeroAnchor: Bool {\n        switch self {\n")
    for p in concrete:
        if p.get("republishesZeroAnchor"):
            out.append("        case .%s: return true\n" % p["swiftCase"])
    out.append("        default: return false\n        }\n    }\n")

    out.append("\n    /// 这个播放器报的 `playing:false` 不可信、要按 `playbackRate > 0` 判在不在播。\n"
               "    /// 只有**实测见过**的播放器为 true。判定本身在 `MediaControlClient.effectivePlaying`,Go 侧同源。\n"
               "    public var playingFromRate: Bool {\n        switch self {\n")
    for p in concrete:
        if p.get("playingFromRate"):
            out.append("        case .%s: return true\n" % p["swiftCase"])
    out.append("        default: return false\n        }\n    }\n")

    out.append("\n    /// 这个 bundle id 属于哪个内置播放器 —— 认不出来(第三方 / 信任列表里的 App /\n"
               "    /// 空值)返回 nil。`.auto` 永远不会被返回:它不对应任何 App。\n"
               "    public static func builtin(forBundleID bundleID: String?) -> PlaybackPlayer? {\n"
               "        guard let bundleID, !bundleID.isEmpty else { return nil }\n"
               "        return allCases.first { $0 != .auto && $0.bundleIdentifier == bundleID }\n"
               "    }\n")
    out.append("}\n")
    return "".join(out)


# ---------------------------------------------------------------- Swift (App target)

def swift_display_name(p):
    d = p["displayName"]
    if "literal" in d:
        return '"%s"' % d["literal"]
    return 'L10n.t("%s")' % d["l10n"]


def swift_tint(p):
    t = p["tint"]
    if "rgb" in t:
        r, g, b = t["rgb"]
        return "Color(red: %s, green: %s, blue: %s)" % (r, g, b)
    if "source" in t:
        return 'sourceColor("%s")' % t["source"]
    return ".secondary"


def render_app_swift(spec, players):
    out = [BANNER_SWIFT,
           "//\n// 展示层的每播放器一行数据。类型本身在 LyrimuseCore(见 PlaybackPlayer+Generated.swift)\n"
           "// —— MediaControlClient / LocalPlaybackSource 也要认它,而它们在被依赖的下层。\n\n"
           "import SwiftUI\n\nimport LyrimuseCore\n\nextension PlaybackPlayer {\n"]

    out.append("    public var displayName: String {\n        switch self {\n")
    for p in players:
        out.append("        case .%s: return %s\n" % (p["swiftCase"], swift_display_name(p)))
    out.append("        }\n    }\n")

    out.append("\n    /// 没装这个 App 时的占位色。品牌色跟「歌词来源」复用同一份(`sourceColor`)——\n"
               "    /// 国内三家本来就是同一批 App,没理由维护第二份配色映射。\n"
               "    public var tintColor: Color {\n        switch self {\n")
    for p in players:
        out.append("        case .%s: return %s\n" % (p["swiftCase"], swift_tint(p)))
    out.append("        }\n    }\n")

    out.append("\n    public var fallbackSymbolName: String {\n        switch self {\n")
    for p in players:
        out.append('        case .%s: return "%s"\n' % (p["swiftCase"], p["fallbackSymbol"]))
    out.append("        }\n    }\n")

    out.append("\n    /// 这台机器没装对应 App 时,`AppIconResolver.icon(bundledResourceName:)` 去找哪张\n"
               "    /// 随包打包的品牌图。nil = 没有这一层,直接落到 tintColor + fallbackSymbolName。\n"
               "    public var bundledIconResourceName: String? {\n        switch self {\n")
    for p in players:
        icon = p.get("bundledIcon")
        out.append("        case .%s: return %s\n" % (p["swiftCase"], '"%s"' % icon if icon else "nil"))
    out.append("        }\n    }\n")

    by_id = {p["id"]: p for p in players}
    for key, name in (("simplifiedChinese", "displayOrderForSimplifiedChinese"),
                      ("default", "displayOrderDefault")):
        ids = spec["displayOrder"][key]
        cases = ", ".join(".%s" % by_id[i]["swiftCase"] for i in ids)
        out.append("\n    public static let %s: [PlaybackPlayer] = [%s]\n" % (name, cases))
    out.append("}\n")
    return "".join(out)


# ----------------------------------------------------------------

def main():
    check = "--check" in sys.argv[1:]
    spec, players, _ = load()
    rendered = {
        GO_FILE: gofmt(render_go(spec, players)),
        CORE_SWIFT: render_core_swift(spec, players),
        APP_SWIFT: render_app_swift(spec, players),
    }
    stale = []
    for rel, text in rendered.items():
        path = ROOT / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            print("  = %s" % rel)
            continue
        if check:
            stale.append(rel)
            print("  ✗ %s 与 shared/players.json 对不上" % rel)
            continue
        path.write_text(text, encoding="utf-8")
        print("  → %s %s" % (rel, "(新建)" if current is None else "(更新)"))
    if check and stale:
        print("\n✗ 生成物过期或被手改。跑 `python3 scripts/gen-players.py` 重新生成后再提交。")
        return 1
    print("\n✓ %d 个内置播放器,两侧生成物与 shared/players.json 一致" % len(players))
    return 0


if __name__ == "__main__":
    sys.exit(main())
