#!/usr/bin/env python3
"""从 shared/feature-list.json 和 shared/settings-catalog.json 生成功能清单:docs/feature-list*.md 三种语言。

# 两份数据

- shared/feature-list.json:手写的功能清单。每项写清楚做什么、在设置里哪个位置(`settings`,按设置搜索目录里的
  面包屑 + 标题引用)、装好后默认开还是关(`default`)。`check` 指向 AppSettings / FeatureSettingsStore 里的
  布尔设置时,这里扫源码核对默认值,写错了就报错。
- shared/settings-catalog.json:设置搜索目录(LyrimuseCore 的 SettingsSearchCatalog)的导出,selftest
  「settings-search」组核它跟代码逐字节一致。清单末尾的「全部设置项」由它生成,每一行设置都在,不会漏。

界面上的字(设置位置的每一级、全部设置项的标题和说明)取自 Localizable.xcstrings,跟 App 一字不差。
设置项的说明取设置页那一行的 `help:`(这个标题在源码和目录里都只出现一次时),没有就取目录里的副标题。

落地页的 /features/ 页(Lyrimuse资料/19-落地页源文件/features.py)导入本文件,用同一个 `load_model`。

CI 跑 `--check`:生成物没被手改、也没忘记重新生成;引用的设置位置都存在;默认值跟代码一致。
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LANGS = ("en", "zh-Hans", "zh-Hant")
DOC_FILES = {"en": "feature-list.md", "zh-Hans": "feature-list.zh-CN.md", "zh-Hant": "feature-list.zh-Hant.md"}
BRANDS = {"ListenBrainz", "Last.fm", "Discord"}

CHROME = {
    "zh-Hans": {
        "title": "Lyrimuse 功能清单",
        "intro": "这份清单列出 Lyrimuse 的每一项功能：做什么、在设置的哪里、装好后默认开着还是关着；最后附上设置窗口里的全部设置项。清单跟代码一起维护，功能有增减时同步更新。",
        "toc": "目录",
        "off_title": "默认关着的功能",
        "off_intro": "下面这些功能装好后不会自己打开，要先去设置里打开（有的还要连上账号或给权限）：",
        "col_feature": "功能",
        "col_where": "在哪里打开",
        "default_on": "默认开启",
        "default_off": "默认关闭",
        "where": "设置位置",
        "index_title": "全部设置项",
        "index_intro": "设置窗口里的每一项，按所在位置列出，共 {n} 项。在设置窗口侧栏顶部的搜索框里输入名称，可以直接跳到那一项。",
        "settings": "设置",
        "labs": "实验室功能",
        "mini_only": "（仅迷你尺寸）",
        "full_only": "（仅完整尺寸）",
        "sep": "：",
        "generated": "由 scripts/gen-feature-list.py 从 shared/feature-list.json 和 shared/settings-catalog.json 生成，改清单请改那两份文件。",
    },
    "en": {
        "title": "Lyrimuse feature list",
        "intro": "This list covers every Lyrimuse feature: what it does, where it lives in Settings, and whether it is on or off after you install; every setting in the Settings window is listed at the end. It is kept with the code and updated whenever features change.",
        "toc": "Contents",
        "off_title": "Off until you turn them on",
        "off_intro": "These features stay off after you install. Turn them on in Settings first (some also need an account or a permission):",
        "col_feature": "Feature",
        "col_where": "Where to turn it on",
        "default_on": "On by default",
        "default_off": "Off by default",
        "where": "Settings",
        "index_title": "Every setting",
        "index_intro": "Every setting in the Settings window, by where it lives: {n} in all. Type a name into the search field at the top of the Settings sidebar to jump straight to it.",
        "settings": "Settings",
        "labs": "Lab Features",
        "mini_only": " (mini size only)",
        "full_only": " (full size only)",
        "sep": ": ",
        "generated": "Generated by scripts/gen-feature-list.py from shared/feature-list.json and shared/settings-catalog.json; edit those files instead.",
    },
    "zh-Hant": {
        "title": "Lyrimuse 功能清單",
        "intro": "這份清單列出 Lyrimuse 的每一項功能：做什麼、在設定的哪裡、安裝後預設開著還是關著；最後附上設定視窗裡的全部設定項目。清單跟程式碼一起維護，功能有增減時同步更新。",
        "toc": "目錄",
        "off_title": "預設關著的功能",
        "off_intro": "下面這些功能安裝後不會自己打開，要先去設定裡打開（有的還要連上帳號或給權限）：",
        "col_feature": "功能",
        "col_where": "在哪裡打開",
        "default_on": "預設開啟",
        "default_off": "預設關閉",
        "where": "設定位置",
        "index_title": "全部設定項目",
        "index_intro": "設定視窗裡的每一項，依所在位置列出，共 {n} 項。在設定視窗側邊欄頂部的搜尋欄位輸入名稱，可以直接跳到那一項。",
        "settings": "設定",
        "labs": "實驗室功能",
        "mini_only": "（僅迷你尺寸）",
        "full_only": "（僅完整尺寸）",
        "sep": "：",
        "generated": "由 scripts/gen-feature-list.py 從 shared/feature-list.json 和 shared/settings-catalog.json 產生，要改清單請改那兩份檔案。",
    },
}

CALL_RE = re.compile(r"\b(SettingsRow|SettingsSubRow|SettingsCardHeader)\(")
STR = r'"((?:[^"\\\n]|\\.)*)"'
ARG_RE = {name: re.compile(name + r":\s*L10n\.t\(" + STR + r"\)") for name in ("title", "help")}
# 目录里当副标题登记、其实是状态提示的字(搜索用得上,当说明会误导)。
STATE_SUBTITLES = {"系统通知已关闭"}


class FeatureListError(Exception):
    pass


def _unescape(s: str) -> str:
    return s.replace('\\n', '\n').replace('\\"', '"').replace('\\\\', '\\')


def _call_args(text: str, start: int) -> str:
    """`start` 是左括号后一位;返回到配对右括号为止的参数文本(跳过字符串字面量)。"""
    depth, i, n = 1, start, len(text)
    while i < n:
        c = text[i]
        if c == '"':
            i += 1
            while i < n and text[i] != '"':
                i += 2 if text[i] == '\\' else 1
        elif c == '(':
            depth += 1
        elif c == ')':
            depth -= 1
            if depth == 0:
                return text[start:i]
        i += 1
    return text[start:]


def _row_help(root: Path) -> dict[str, list[str | None]]:
    """设置页每一行的标题 → 每个调用点的 `help:` 字面量(没有就是 None)。"""
    found: dict[str, list[str | None]] = {}
    for path in sorted((root / "lyrimuse/Sources/lyrimuse").rglob("*.swift")):
        text = path.read_text(encoding="utf-8")
        for m in CALL_RE.finditer(text):
            args = _call_args(text, m.end())
            title = ARG_RE["title"].search(args)
            if not title:
                continue
            d = ARG_RE["help"].search(args)
            found.setdefault(_unescape(title.group(1)), []).append(_unescape(d.group(1)) if d else None)
    return found


def _labs_destinations(root: Path) -> set[str]:
    text = (root / "lyrimuse/Sources/lyrimuse/AccountLinkingTab.swift").read_text(encoding="utf-8")
    m = re.search(r"var livesInLabs: Bool \{\s*switch self \{\s*case ([^:]+): return true", text)
    if not m:
        raise FeatureListError("AccountLinkingTab.swift 里认不出 livesInLabs(改名了就改这里)")
    return {"account:" + c.strip().lstrip(".") for c in m.group(1).split(",")}


def _default_from_source(root: Path, check: dict) -> bool:
    if "appSetting" in check:
        name = check["appSetting"]
        text = (root / "lyrimuse/Sources/lyrimuse/Settings/AppSettings.swift").read_text(encoding="utf-8")
        values = set()
        for m in re.finditer(r"Keys\." + re.escape(name) + r"\)\s*as\?\s*Bool\)\s*\?\?\s*(true|false|Self\.(\w+))", text):
            if m.group(2):
                s = re.search(r"static let " + re.escape(m.group(2)) + r"(?:\s*:\s*Bool)?\s*=\s*(true|false)\b", text)
                if not s:
                    raise FeatureListError(f"AppSettings.{m.group(2)} 认不出是 true 还是 false")
                values.add(s.group(1))
            else:
                values.add(m.group(1))
        where = f"AppSettings.{name}"
    elif "featureFlag" in check:
        name = check["featureFlag"]
        text = (root / "lyrimuse/Sources/lyrimuse/Settings/FeatureSettingsStore.swift").read_text(encoding="utf-8")
        values = set(re.findall(r"\b" + re.escape(name) + r" = f\." + re.escape(name) + r" \?\? (true|false)\b", text))
        where = f"FeatureSettingsStore.{name}"
    else:
        raise FeatureListError(f"check 只认 appSetting / featureFlag:{check}")
    if len(values) != 1:
        raise FeatureListError(f"{where} 的默认值认不出来(找到 {sorted(values) or '0 处'})")
    return values.pop() == "true"


def load_model(root: Path = ROOT) -> dict:
    features = json.loads((root / "shared/feature-list.json").read_text(encoding="utf-8"))
    catalog = json.loads((root / "shared/settings-catalog.json").read_text(encoding="utf-8"))["entries"]
    strings = json.loads((root / "lyrimuse/Localization/Localizable.xcstrings").read_text(encoding="utf-8"))["strings"]
    labs = _labs_destinations(root)
    helps = _row_help(root)

    def tr(key: str, lang: str) -> str:
        if lang == "zh-Hans" or key in BRANDS:
            return key
        try:
            return strings[key]["localizations"][lang]["stringUnit"]["value"]
        except KeyError:
            raise FeatureListError(f"Localizable.xcstrings 里没有「{key}」的 {lang}") from None

    def has_all(key: str) -> bool:
        loc = strings.get(key, {}).get("localizations", {})
        return all(loc.get(lang, {}).get("stringUnit", {}).get("value") for lang in ("en", "zh-Hant"))

    def location(entry: dict, with_title: bool, prefix: bool) -> dict:
        keys = (["设置"] if prefix else []) + (["实验室功能"] if entry["dest"] in labs else []) \
            + entry["path"] + ([entry["title"]] if with_title else [])
        return {lang: " › ".join(tr(k, lang) for k in keys) for lang in LANGS}

    title_count: dict[str, int] = {}
    for e in catalog:
        title_count[e["title"]] = title_count.get(e["title"], 0) + 1

    def entry_desc(entry: dict) -> dict | None:
        # 同名的行(三个面各有「宽度」)分不清哪条 help 属于哪一行,只认标题全仓唯一的。
        sites = helps.get(entry["title"], [])
        text = sites[0] if len(sites) == 1 and title_count[entry["title"]] == 1 else None
        if not text:
            text = entry.get("subtitle")
            if text in STATE_SUBTITLES:
                text = None
        if not text or "%" in text or not has_all(text):
            return None
        out = {}
        for lang in LANGS:
            lines = [l.strip() for l in tr(text, lang).split("\n") if l.strip()]
            joined = ""
            for line in lines:
                if joined:
                    joined += " " if lang == "en" else ("" if joined[-1] in "。；：！？" else "；")
                joined += line
            out[lang] = joined
        return out

    by_ref = {}
    for e in catalog:
        by_ref.setdefault(tuple(e["path"] + [e["title"]]), e)

    seen_ids = set()
    sections = []
    for sec in features["sections"]:
        items = []
        for f in sec["features"]:
            fid = f["id"]
            if fid in seen_ids:
                raise FeatureListError(f"功能 id 重复:{fid}")
            seen_ids.add(fid)
            for field in ("title", "desc"):
                missing = [l for l in LANGS if not f.get(field, {}).get(l)]
                if missing:
                    raise FeatureListError(f"{fid} 的 {field} 缺 {missing}")
            default = f.get("default")
            if default not in (None, "on", "off"):
                raise FeatureListError(f"{fid} 的 default 只能是 on / off / 不写:{default!r}")
            if "check" in f:
                if default is None:
                    raise FeatureListError(f"{fid} 写了 check 却没写 default")
                actual = _default_from_source(root, f["check"])
                if actual != (default == "on"):
                    raise FeatureListError(f"{fid} 写的是默认 {default},代码里是 {'on' if actual else 'off'}({f['check']})")
            refs = []
            for ref in f.get("settings", []):
                entry = by_ref.get(tuple(ref))
                if not entry:
                    raise FeatureListError(f"{fid} 引用的设置位置不在目录里:{' › '.join(ref)}")
                refs.append(location(entry, with_title=True, prefix=False))
            items.append({"id": fid, "title": f["title"], "desc": f["desc"], "default": default, "settings": refs})
        sections.append({"id": sec["id"], "title": sec["title"], "features": items})

    groups: list[dict] = []
    by_path: dict[str, dict] = {}
    for e in catalog:
        path = location(e, with_title=False, prefix=False)
        group = by_path.get(path["zh-Hans"])
        if group is None:
            group = by_path[path["zh-Hans"]] = {"path": path, "items": []}
            groups.append(group)
        group["items"].append({
            "title": {lang: tr(e["title"], lang) for lang in LANGS},
            "desc": entry_desc(e),
            "mini": e.get("lyricsWindowMini"),
        })
    missing = [l for l in LANGS if not features.get("about", {}).get(l)]
    if missing:
        raise FeatureListError(f"about 缺 {missing}")
    return {"about": features["about"], "sections": sections, "index": groups, "count": len(catalog),
            "settings_label": {lang: tr("设置", lang) for lang in LANGS}}


def _anchor(kind: str, ident: str) -> str:
    return f"{kind}-{ident}"


def _md_escape(s: str) -> str:
    return s.replace("|", "\\|")


def render_markdown(model: dict, lang: str) -> str:
    t = CHROME[lang]
    out = [f"<!-- {t['generated']} -->", "", f"# {t['title']}", ""]
    switch = []
    for other, label in (("en", "English"), ("zh-Hans", "简体中文"), ("zh-Hant", "繁體中文")):
        switch.append(label if other == lang else f"[{label}]({DOC_FILES[other]})")
    out += [" · ".join(switch), "", model["about"][lang], "", t["intro"], "", f"## {t['toc']}", ""]
    out.append(f"- [{t['off_title']}](#{_anchor('section', 'off-by-default')})")
    for sec in model["sections"]:
        out.append(f"- [{sec['title'][lang]}](#{_anchor('section', sec['id'])})")
    out.append(f"- [{t['index_title']}](#{_anchor('section', 'all-settings')})")

    out += ["", f'<a id="{_anchor("section", "off-by-default")}"></a>', "", f"## {t['off_title']}", "", t["off_intro"], "",
            f"| {t['col_feature']} | {t['col_where']} |", "|---|---|"]
    for sec in model["sections"]:
        for f in sec["features"]:
            if f["default"] != "off":
                continue
            where = f"{model['settings_label'][lang]} › {f['settings'][0][lang]}" if f["settings"] else "—"
            out.append(f"| [{_md_escape(f['title'][lang])}](#{_anchor('feature', f['id'])}) | {_md_escape(where)} |")

    for sec in model["sections"]:
        out += ["", f'<a id="{_anchor("section", sec["id"])}"></a>', "", f"## {sec['title'][lang]}"]
        for f in sec["features"]:
            out += ["", f'<a id="{_anchor("feature", f["id"])}"></a>', "", f"### {f['title'][lang]}", "", f["desc"][lang], ""]
            if f["default"]:
                out.append(f"- {t['default_on'] if f['default'] == 'on' else t['default_off']}")
            for ref in f["settings"]:
                out.append(f"- {t['where']}{t['sep']}{ref[lang]}")
            if out[-1] == "":
                out.pop()

    out += ["", f'<a id="{_anchor("section", "all-settings")}"></a>', "", f"## {t['index_title']}", "",
            t["index_intro"].format(n=model["count"])]
    for g in model["index"]:
        out += ["", f"### {g['path'][lang]}", ""]
        for item in g["items"]:
            line = f"- **{item['title'][lang]}**"
            if item["mini"] is not None:
                line += t["mini_only"] if item["mini"] else t["full_only"]
            if item["desc"]:
                line += f"{t['sep']}{item['desc'][lang]}"
            out.append(line)
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    try:
        model = load_model(ROOT)
    except FeatureListError as e:
        print(f"!! {e}", file=sys.stderr)
        return 1
    stale = []
    for lang, name in DOC_FILES.items():
        path = ROOT / "docs" / name
        text = render_markdown(model, lang)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(text, encoding="utf-8")
            print(f"写入 {path.relative_to(ROOT)}")
    if stale:
        print("!! 这些文件跟数据对不上,跑一遍 python3 scripts/gen-feature-list.py:" + "、".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
