// Code generated by scripts/gen-lyric-notices.py from shared/lyric-notices.json; DO NOT EDIT.
//
// 改规则:改那份 JSON → 跑 `python3 scripts/gen-lyric-notices.py`。CI 跑 `--check` 对账,手改这里会红。

package main

// drop = true:rule 这一条必须命中;false:任何一条规则都不许命中。
var lyricNoticeExamples = []struct {
	rule string
	text string
	drop bool
}{
	{"translation-copyright", "TME享有本翻译作品的著作权", true},
	{"translation-copyright", "TME享有翻译作品的著作权", true},
	{"translation-copyright", "腾讯享有本翻译作品的著作权", true},
	{"translation-copyright", "本翻译作品的著作权归QQ音乐所有", true},
	{"translation-copyright", "騰訊享有本翻譯作品的著作權", true},
	{"translation-copyright", "翻译你眼里的作品", false},
	{"translation-copyright", "著作权", false},
	{"qq-copyright", "QQ音乐享有本翻译作品的著作权", true},
	{"qq-copyright", "我在QQ音乐上听到这首歌", false},
	{"translator-notice", "以下歌词翻译由文曲大模型提供", true},
	{"translator-notice", "以下歌词翻译由微信翻译提供", true},
	{"translator-notice", "以下歌词翻译由微信翻译+文曲大模型提供", true},
	{"translator-notice", "翻译由我提供", false},
	{"unlicensed-use", "未经著作权人许可不得翻录翻唱或使用", true},
	{"unlicensed-use", "未经著作权人许可 不得翻录翻唱或使用", true},
	{"unlicensed-use", "（未经许可,不得翻唱或使用）", true},
	{"unlicensed-use", "未经允许的心动", false},
	{"forbidden-use", "（未经许可,不得翻唱或使用）", true},
	{"forbidden-use", "本作品不得转载", true},
	{"forbidden-use", "我不得不承认", false},
	{"rights-reserved-zh", "版权所有 翻录必究", true},
	{"rights-reserved-zh", "保留所有权利", true},
	{"rights-reserved-zh", "我要赌上我的版权", false},
	{"rights-reserved-en", "All Rights Reserved", true},
	{"rights-reserved-en", "Unauthorized reproduction is prohibited", true},
	{"rights-reserved-en", "All my rights reserved for you", false},
	{"license-obtained", "【本音乐作品已获得正版授权】", true},
	{"license-obtained", "已通过「腾讯音乐·启明星」获得官方翻唱授权", true},
	{"license-obtained", "（本作品已经过词曲著作权利方授权）", true},
	{"license-obtained", "【英文版翻译自花粥《二十岁的某一天》, 已获词曲授权】", true},
	{"license-obtained", "本作品已獲得正版授權", true},
	{"license-obtained", "谁授权你这样对我", false},
	{"license-obtained", "我们经过那条街", false},
	{"license-official", "（此版本为正式授权翻唱作品）", true},
	{"license-official", "我把心授权给你", false},
	{"subtitle-generated", "本字幕由AI语音对齐技术生成", true},
	{"subtitle-generated", "本字幕由TME AI技术生成", true},
	{"subtitle-generated", "本字幕由酷狗AI语音识别技术生成", true},
	{"subtitle-generated", "新的世界正在生成", false},
	{"company-provided", "由星演国际有限公司提供", true},
	{"company-provided", "由你决定", false},
	{"company-provided", "由我来提供温暖的怀抱", false},
	{"company-provided", "我会努力提供", false},
	{"company-provided", "为反对纳粹的派对提供房间", false},
	{"company-provided", "无声的贡献有天会懂", false},
	{"sample-credit", "Contains an interpolation of “Weak” written by Brian Alexander Morgan,", true},
	{"sample-credit", "Contains samples from \"Song\" performed by Someone", true},
	{"sample-credit", "Contains interpolations from \"Physical\" written by Steve Kipner", true},
	{"sample-credit", "It contains all of my love", false},
	{"sample-credit", "Contains multitudes, like me", false},
	{"sample-credit", "Contains samples offered", false},
}
